{% set name = "oslo.context" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oslo_context-{{ version }}.tar.gz
  sha256: 151e8228982d3885ed3fed288e8cddb26f894fb40cb8132129fa9e5b3e0ef0bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pbr !=2.1.0,>=2.0.0
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pbr !=2.1.0,>=2.0.0
    - debtcollector >=1.2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - oslo_context

about:
  home: https://docs.openstack.org/oslo.context/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: The Oslo context library has helpers to maintain useful information about a request context.
  dev_url: https://docs.openstack.org/infra/manual/developers.html

extra:
  recipe-maintainers:
    - tschoonj
